name: "Statusfy Incident"
on:
  issue_comment:
  issues:
    types: [opened, edited, closed, reopened, labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate incident
      uses: devkanro/setup-statusfy@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
    - name: Build the static site.
      run: |
        npm install
        npm run generate
